---
- name: "show remote environment"
  shell: env

- name: "copy backend binaries"
  become: yes
  synchronize:
    src: ../../backend/dist
    dest: /home/ubuntu/udapeople_app
    recursive: true

- name: "copy node_modules"
  become: yes
  synchronize:
    src: ../../backend/node_modules
    dest: /home/ubuntu/udapeople_app
    recursive: true

- name: "delete anything that might already be running"
  become: true
  command: pm2 delete all
  ignore_errors: true

- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: true
  apt:
    autoremove: yes

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy index test page
  template:
    src: "files/index.js"
    dest: "~/web/index.js"

- name: Executing node
  shell: |
    pm2 start ~/web/index.js -f

- name: "start server"
  become: true
  command: pm2 start -f ./main.js
  args:
    chdir: /home/ubuntu/udapeople_app/dist
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    TYPEORM_MIGRATIONS_DIR: "./src/migrations"
    TYPEORM_MIGRATIONS: "./src/migrations/*.ts"
    TYPEORM_ENTITIES: "./src/modules/domain/**/*.entity.ts"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"